### ISSUE TITLE
Could I show the number of video and number of photo separate in each album ? 

### ISSUE THREAD

**Issue by HTKT** [guillermomuntaner/GMImagePicker#16]
Your lib is showing the total number of item in each album. Now i want to customize them to number of photo and number of video ? Is it doable? Please give me some advice. Thanks in advance.

**Comment by guillermomuntaner** [comment]
Yes, it is doable! (but it is not implemented, so you should write your own version)

You need to replace the following method inside the GMAlbumsViewController.m file
- (NSString *)tableCellSubtitle:(PHFetchResult*)assetsFetchResult

Instead of returning a simple number, there your can return a more complex NSString with the number of photos & videos.

Hope it helps you.
